title: 点名器
email: himself6565@gmail.com
title: "点名器"
description: 
  "上课点名器"
url: "http://random.himself65.com"
baseurl: "" # Don't change


zhihu_username:     liu-jing-zong-32
github_username:    tjujingzong


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# gems: [jekyll-paginate]

# Google Analytics
ga_track_id: 'UA-110549153-1'            # Format: UA-xxxxxx-xx
ga_domain: Himself65

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
